version: "3.9"
services:
  server:
    build: ./server
    env_file: database.conf
    ports: 
    - 5001:5001
    volumes: 
    - ./server:/app
  web:
    build: ./client
    ports: 
      - 3000:3000
    depends_on: 
      - server
  database: 
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
