version: "3.9"
services:
  server:
    build: ./server
    env_file: 
    - database.conf
    - .env
    ports: 
    - ${PORT_SERVER_OUT}:${PORT_SERVER_IN}
    volumes: 
    - ./server:/app
    depends_on:
      - database
  web:
    build: ./client
    env_file:
      - .env
    ports: 
      - ${PORT_CLIENT_OUT}:${PORT_CLIENT_IN}
    depends_on: 
      - server
  database: 
    image: postgres:latest
    env_file: 
    - database.conf
    - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume:
